## 디버깅 로그 레벨 조절
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

server:
  port: 8888
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/celover?serverTimezone=Asia/Seoul
    username: celover
    password: celover
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # create로 되어 있으면 프로젝트를 실행할때마다 생성되기 때문에 최초만 create 로 설정해주고, 그 이후는 update로 해주어야 한다.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #엔티티(테이블)를 만들 때 변수명 그대로 필드에 넣으라는 의미
        use-new-id-generator-mappings: false # 여기서 true를 하면 JPA가 설정하는 기본 넘버링 전략을 따라간다는 의미임
                                                                         # 현재는 따라가지 않고, 별도로 넘버링 전략을 쓰겠다는 의미가 된다.
    show-sql: true # console 창에 sql에 대한 데이터를 표현해준다.
    properties:
      hibernate.format_sql: true # console 창에 생성, 수정, 삭제, 등등 sql의 동작에 대한 부분들이 표현될 때 행구분을 하면서 보여준다.

  jackson:
    serialization:
      fail-on-empty-beans: false
      
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 785937440395-5a96rf6lhkjgln50rt8kgb9ukmo9k60n.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          kakao:
            client-id: d15d0ec9bd2e7e5bd2904659955fbb98
            client-secret: 6dzMLEZMFaEeUJJF9tVWRt3Y5Rm0uHOt
            redirect-uri: http://localhost:8888/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: 
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
          naver:
            client-id: 0BaJ2YFdJYyQtzIPoAoH
            client-secret: _Xp4E7iZB_
            redirect-uri: http://localhost:8888/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: 
              - name
              - email
            client-name: Naver
            
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute : id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
celover:
  key: celover
             